name: 📊 Track Mod Downloads History

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  update-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch download_counts.json
        run: |
          curl -s \
            https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/6ce43b260868a4bea1bd081b039b7b66c13d06cc/download_counts.json \
            -o download_counts.json

      - name: Validate JSON
        run: jq . download_counts.json

      - name: Build new entry
        id: build_entry
        run: |
          TODAY=$(date +%F)
          ENTRY=$(jq -c \
            --arg date "$TODAY" \
            '{ date: $date,
               KerbalChecklists: (.KerbalChecklists // 0),
               WasdMainMenu: (.WasdMainMenu // 0),
               "RP-1-Checklists": (.["RP-1-Checklists"] // 0)
             }' download_counts.json)
          echo "::set-output name=entry::$ENTRY"

      - name: Ensure history.json exists
        run: |
          if [ ! -f history.json ] || [ ! -s history.json ]; then
            echo '[]' > history.json
          fi

      - name: Append to history.json
        run: |
          ENTRY="${{ steps.build_entry.outputs.entry }}"
          jq --argjson e "$ENTRY" '. + [ $e ]' history.json > tmp.json
          mv tmp.json history.json

      - name: Commit & Push history.json
        uses: EndBug/add-and-commit@v9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add: history.json
          message: "📈 Update download history for ${{ fromJson(steps.build_entry.outputs.entry).date }}"
