name: Track Mod Downloads

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Every day at noon UTC
  push:
    paths:
      - '.github/workflows/track-downloads.yml'

jobs:
  update-history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch CKAN download_counts.json
        run: curl -s https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/main/download_counts.json -o download_counts.json

      - name: Parse and update history
        run: |
          MODS=("KerbalChecklists" "WasdMainMenu" "RP-1-Checklists")
          TODAY=$(date +%F)

          # Fetch download_counts.json and load it
          DOWNLOADS_JSON=$(cat download_counts.json)

          # Construct a new entry in JSON format using jq
          NEW_ENTRY=$(jq -n \
            --arg date "$TODAY" \
            --argjson downloads "$DOWNLOADS_JSON" \
            '{
              date: $date
            } + (reduce ["KerbalChecklists", "WasdMainMenu", "RP-1-Checklists"][] as $mod ({}; .[$mod] = ($downloads[$mod] // 0)))')

          # Append the new entry to history.json or create the file
          if [ -f history.json ]; then
            jq --argjson new_entry "$NEW_ENTRY" '. + [$new_entry]' history.json > combined.json
          else
            jq -n --argjson new_entry "$NEW_ENTRY" '[ $new_entry ]' > combined.json
          fi

          mv combined.json history.json

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "📊 Update download history"
          add: "history.json"
